export { default as FormModal } from './FormModal'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as UserCenter } from './UserCenter'
// export { default as ProductList } from './ProductList'
// export { default as UploadAvatar } from './UploadAvatar'
